name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt-get install -y build-essential libgtest-dev
    - name: make
      run: make
    - name: chmod
      run: chmod +x ./shannon ./tests
    - name: shannon_alg
      run: ./shannon
    - name: clean
      run: make clean
